#!/usr/bin/python3
# This function raise a name exception with a message
def raise_exception_msg(message=""):
    raise NameError(message)
